#!/usr/bin/env python3
"""Generate golden-srs.json from the reference scheduler in drill.py.

drill.py is the reference implementation; webapp/srs.js is a hand-written
port of it. test-srs.js replays these vectors through srs.js and asserts
every field of every step matches exactly -- the two sides grade the same
card the same way or a user's schedule silently diverges depending on
which device they studied on.

Vectors:
  * every answer sequence up to length 6 (126 of them), plus a 25-correct
    streak that must walk the documented ladder and hit the 180-day cap:
      10m, 30m, 2h, 1d, 2.5d, 6.25d, 15.6d, 39.1d, 97.7d, then capped
  * merge cases for sync.merge_entry, which srs.js mirrors as mergeEntry --
    order of arrival must never lose answers

Times are generated under TZ=UTC and test-srs.js forces TZ=UTC too. This
is deliberate: Python schedules with naive wall-clock arithmetic and JS
with epoch arithmetic, which agree except across a DST jump inside an
interval. UTC has no jumps, so the comparison is exact.

CI regenerates this file and fails if it differs from the committed copy,
so a change to the scheduler cannot slip past the port unnoticed.
"""

import itertools
import json
import os
import sys
import time

os.environ["TZ"] = "UTC"
time.tzset()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from datetime import datetime  # noqa: E402

import drill  # noqa: E402
import sync   # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "golden-srs.json")

# Fixed, timezone-boundary-free moment; every answer in a sequence is
# graded exactly SPACING_MIN minutes after the previous one.
BASE_NOW = datetime.fromisoformat("2026-01-05T09:00:00")
SPACING_MIN = 7

LADDER = [10, 30, 120, 1440, 3600, 9000, 22500, 56250, 140625]


def fresh():
    return {"due": "1970-01-01T00:00:00", "step": 0, "interval_min": 0,
            "ease": drill.EASE_START, "reps": 0, "lapses": 0}


def replay(seq):
    from datetime import timedelta
    entry = fresh()
    steps = []
    for k, correct in enumerate(seq):
        now = BASE_NOW + timedelta(minutes=k * SPACING_MIN)
        entry = drill.grade(entry, correct, now)
        steps.append(dict(entry))
    return steps


def sequences():
    for n in range(1, 7):
        for combo in itertools.product([True, False], repeat=n):
            yield list(combo)
    yield [True] * 25          # the ladder, into the interval cap


def entry_variant(due_min_offset, step, interval, ease, reps, lapses):
    from datetime import timedelta
    return {
        "due": (BASE_NOW + timedelta(minutes=due_min_offset))
        .isoformat(timespec="seconds"),
        "step": step, "interval_min": interval, "ease": ease,
        "reps": reps, "lapses": lapses,
    }


def merge_cases():
    """Entries chosen to hit every branch of the merge rule."""
    a = entry_variant(60, 4, 1440, 2.5, 3, 0)     # count 3
    b = entry_variant(30, 1, 10, 2.3, 2, 2)       # count 4 -> b wins
    tie_early = entry_variant(10, 2, 30, 2.5, 2, 0)
    tie_late = entry_variant(500, 3, 120, 2.1, 1, 1)   # same count, later due
    fresh_e = fresh()
    cases = []
    for x, y in [(a, b), (b, a), (tie_early, tie_late), (tie_late, tie_early),
                 (a, a), (fresh_e, a), (a, fresh_e),
                 (None, a), (a, None), (None, None)]:
        cases.append({"a": x, "b": y, "merged": sync.merge_entry(x, y)})
    return cases


def main():
    vectors = []
    for seq in sequences():
        vectors.append({"seq": seq, "steps": replay(seq)})

    streak = vectors[-1]["steps"]
    intervals = [s["interval_min"] for s in streak]
    assert intervals[:len(LADDER)] == LADDER, intervals[:len(LADDER)]
    assert all(i == 259200 for i in intervals[len(LADDER):]), intervals
    assert len(vectors) == 127, len(vectors)

    doc = {
        "note": "Generated by gen-golden.py from drill.py. Do not edit.",
        "baseNow": BASE_NOW.isoformat(timespec="seconds"),
        "spacingMin": SPACING_MIN,
        "ladder": LADDER,
        "maxIntervalMin": drill.MAX_INTERVAL_MIN,
        "vectors": vectors,
        "mergeCases": merge_cases(),
    }
    with open(OUT, "w") as fh:
        json.dump(doc, fh, indent=1)
        fh.write("\n")
    print(f"wrote {OUT}: {len(vectors)} vectors, "
          f"{len(doc['mergeCases'])} merge cases")


if __name__ == "__main__":
    main()
